grpcport: 9000
storetype: aws
storeconfig:
  db:
    uri: mongodb://localhost:27017
    # Same as the mongodb root username & password in docker-compose.yml
    user: root
    password: example
    databasename: golan
  elasticsearch:
    uri: elasticsearchuri
    user: elasticsearchuser
    password: elasticsearchpassword