grpcport: 9000
storetype: aws
storeconfig:
  db:
    uri: mongodb://localhost:27017
    user: dynamodbuser
    password: dynamodbpassword
    databasename: golan
  elasticsearch:
    uri: elasticsearchuri
    user: elasticsearchuser
    password: elasticsearchpassword