storetype: aws
storeconfig:
  dynamodburi: dynamodburi
  dynamodbuser: dynamodbuser
  dynamodbpassword: dynamodbpassword
  elasticsearchuri: elasticsearchuri
  elasticsearchuser: elasticsearchuser
  elasticsearchpassword: elasticsearchpassword